color: "#6FCAF3"
copyright: "Copyright &copy; 2021 Blackbee. All Rights Reserved."
footer:
  - title: About
    content: Blackbee Machine Intelligence
  - title: Recent Blog Posts
    recents: blog
    recentCount: 7
  - title: Contact Us
    contact: true
recent_posts:
  enable: true
