baseURL: https://www.blackbee.ai/
languageCode: en-us
title: blackbee
theme: Eclectic
author:                                       # Information about the website author
  twitter: "https://twitter.com/blackbee_ai"
#  email: "benny@blackbee.ai"
  name: "Blackbee"
  location: Antwerp, Belgium
#  phone: +32 475 82 18 04
  hours: "**Mon-Fri:** 9:00AM - 5:00PM, CET"

menu:                                         # Menu placement
  main:                                       #    - Name of the menu
    - identifier: about                       #       - Identifier
      name: About                             #       - Display name (theme specific key)
      url: /about                             #       - Target URL
      weight: 1                               #       - Sorting order
    - identifier: contact
      name: Contact
      url: /contact
      weight: 2
params:                                       # Theme specific parameters
  color: "#71B180"
  copyright: "Copyright &copy; 2021 Blackbee. All Rights Reserved."
  footer:
    - title: About
      content: Blackbee Machine Intelligence
    - title: Recent Blog Posts
      recents: blog
      recentCount: 7
    - title: Contact Us
      contact: true